Fix for paths with embedded spaces
Resolves FileNotFound exception that was thrown with embedded spaces on a Windows path that were being converted to URL format.   

2022-08-23 11:10:46.361+0000 [id=14]    SEVERE  h.p.v.JVMVersionComparator$MasterBytecodeMajorVersionNumberGetter#get: Issue while reading Jenkins.class bytecode level
java.io.FileNotFoundException: C:\Program%20Files%20(x86)\Jenkins\war\WEB-INF\lib\jenkins-core-2.346.3.jar (The system cannot find the path specified)